language: node_js
node_js:
- node
- '0.10'
before_deploy:
- openssl aes-256-cbc -K $encrypted_cf5132444c1b_key -iv $encrypted_cf5132444c1b_iv
  -in manifest-validator-appspot.json.enc -out manifest-validator-appspot.json -d
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: manifest-validator-appspot.json
  project: manifest-validator
  default: true
  on:
    branch: master
    node: '0.10'
