runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(check)?
  script: main.app
  secure: always

- url: /*
  static_dir: static/
  secure: always

libraries:
- name: lxml
  version: "2.3.5"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^node_modules/.*$
