runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: main.app
  secure: always

- url: /*
  static_dir: static/
  secure: always

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^node_modules/.*$
